modal-added
js-tasks-ru/htmlcss-20221107_stepan-vasiliuk pull request #13
Opened 2022-12-01 10:43 UTC by stepan-vasiliuk

2022-12-01 10:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-02 08:44 UTC, GSemikozov requested changes

2022-12-02 08:44 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    opacity: 0.5;
лишнее

2022-12-04 13:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-06 07:13 UTC, GSemikozov approved these changes

2022-12-06 07:13 UTC, merged