Component page added
js-tasks-ru/htmlcss-20221107_stepan-vasiliuk pull request #14
Opened 2022-12-05 11:22 UTC by stepan-vasiliuk

2022-12-05 11:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-06 07:15 UTC, GSemikozov requested changes

2022-12-06 07:15 UTC, GSemikozov commented on components/page/page.css
> +    display: grid;
это ведь переиспользуемый блок, получается на Главной теперь работать не будет?
вот эти переопределения можно описать через модификатор, например .page_inner

2022-12-06 07:15 UTC, GSemikozov commented on components/page/page.css
> +.main {
это относится к блоку main а не page

2022-12-06 07:15 UTC, GSemikozov commented on components/page/page.css
> +.main__inner {
и это

2022-12-06 07:15 UTC, GSemikozov commented on components/page/page.css
> +.menu {
а это - menu

2022-12-06 07:15 UTC, GSemikozov commented on components/page/page.css
> +.component {
а это блок component а не page

2022-12-06 12:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-07 16:47 UTC, GSemikozov requested changes

2022-12-07 16:47 UTC, GSemikozov commented on components/page/page.css
grid-area: main; - сюда же

2022-12-08 12:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-08 22:15 UTC, GSemikozov approved these changes

2022-12-08 22:15 UTC, merged