Skeleton-markup
js-tasks-ru/htmlcss-20221107_stepan-vasiliuk pull request #8
Opened 2022-11-21 06:49 UTC by stepan-vasiliuk

2022-11-21 06:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-21 21:30 UTC, GSemikozov requested changes

2022-11-21 21:30 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    min-width: 515px;
это лишнее, удалим

2022-11-21 21:30 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
у линий ширину лучше задавать в процентах

2022-11-22 16:42 UTC, GSemikozov approved these changes

2022-11-22 16:42 UTC, merged